#ifndef LAYOUT_DEFINES_H
#define LAYOUT_DEFINES_H

#define CENTER_BACKGROUND_COLOR LIGHTGREY
#define NR_VISIBLE_MENU_ITEMS 5

#define V_PADDING_BOTTOM_SECTION 4

#define SOFTKEY_COLOR WHITE
#define SOFTKEY_BACKGROUND_COLOR RED

#define TOP_BAR_TITLE_COLOR WHITE
#define TOP_BAR_BACKGROUND_COLOR RED
#define V_PADDING_TOP_SECTION 4
#define MY_FONT 2


#define BOTTOM_BAR_BACKGROUND_COLOR RED
#define V_PADDING_BOTTOM_SECTION 4

// high contrast theme
//#define MENU_ITEM_TEXT_COLOR WHITE
//#define MENU_ITEM_BACKGROUND_COLOR BLACK
//#define MENU_ITEM_HIGHLIGHTED_TEXT_COLOR BLACK
//#define MENU_ITEM_HIGHLIGHTED_BACKGROUND_COLOR WHITE

// grey levels theme
#define MENU_ITEM_TEXT_COLOR DARKGREY
#define MENU_ITEM_BACKGROUND_COLOR LIGHTGREY
#define MENU_ITEM_HIGHLIGHTED_TEXT_COLOR BLACK
#define MENU_ITEM_HIGHLIGHTED_BACKGROUND_COLOR WHITE

// TODO: replace LCD.height and font get Width with defines


#endif 

